version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: chatgpt
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql:/var/lib/mysql